### ISSUE TITLE
Cannot find module 'is-extglob'

### ISSUE THREAD

**Issue by veggiemonk** [mikz/jspm-dev-server#3]
Hi,

After installing `jspm-dev-server` locally with `npm`, I tried to start the server 

``` sh
❯ node ./node_modules/.bin/jspm-dev-server
/home/veggiemonk/code/ichinisan/node_modules/.store/jspm-dev-server@0.2.0/_/bin/jspm-dev-server:37
    throw error
    ^

Error: Cannot find module 'is-extglob'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/veggiemonk/code/ichinisan/node_modules/.store/is-glob@2.0.1/_/index.js:8:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

When it is installed globally `npm -g i jspm-dev-server` , the server starts.

**Comment by mikz** [comment]
Could you try the latest version? `0.4.0`. I'm successfully using it as a local instal just fine.

**Comment by jonschlinkert** [comment]
I just found this issue (I maintain is-extglob). fwiw this seems to happen a lot with random packages with newer versions of npm. 95% of the time if you just delete `node_modules` and reinstall everything it will fix the issue

**Comment by veggiemonk** [comment]
Thank you both :smile:
