### ISSUE TITLE
Error: Must provide a proper URL as target

### ISSUE THREAD

**Issue by veggiemonk** [mikz/jspm-dev-server#4]
Hi,

When I go to https://localhost:3000, there is an error inside the `http-proxy` dependency.

``` sh
❯ jspm-dev-server
[jspm-dev-server] serving /home/veggiemonk/code/ichinisan on https://localhost:3000
/usr/local/lib/node_modules/jspm-dev-server/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: Must provide a proper URL as target
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/jspm-dev-server/node_modules/http-proxy/lib/http-proxy/index.js:68:35)
    at /usr/local/lib/node_modules/jspm-dev-server/index.js:72:13
    at SendStream.error (/usr/local/lib/node_modules/jspm-dev-server/node_modules/serve-static/index.js:116:9)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (/usr/local/lib/node_modules/jspm-dev-server/node_modules/send/index.js:245:17)
    at SendStream.onStatError (/usr/local/lib/node_modules/jspm-dev-server/node_modules/send/index.js:356:12)
    at onstat (/usr/local/lib/node_modules/jspm-dev-server/node_modules/send/index.js:621:26)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Apparently, it doesn't work if there is no `--proxy https://localhost:whatever` argument.

Is this the default use case ?

**Comment by mikz** [comment]
It was not the main use case. It was a bug and it was fixed.
