### ISSUE TITLE
jspm beta requirement?

### ISSUE THREAD

**Issue by kwesterfeld** [mikz/jspm-dev-server#6]
I am using the jspm-dev-server for development, but dont want to upgrade jspm.  Why is the dev server pulling in jspm beta?  I'm not sure I understand how the browser build is required?

**Comment by kwesterfeld** [comment]
I see you are using the jspm config libraries to determine the base url.   I would wonder if perhaps you could lower the jspm version requirement to the stable version?  I am worried about having multiple copies of jspm.

Thanks

**Comment by mikz** [comment]
I didn't want to support the stable release, because I don't use it anywhere. 

If you could make it work with the stable version, the PR is most welcome! But I'm not going to work on it, because 0.17 is pretty close to release.

**Comment by kwesterfeld** [comment]
I am able to use version 0.3.1 of jspm-dev-server with the latest JSPM beta, but the 0.4.0 version fails with:

```
> jspm-dev-server --proxy http://localhost:8182 --port 8183 --ignore smc/jspm_packages

...ui/node_modules/jspm-dev-server/bin/jspm-dev-server:31
options.baseURL = jspmConfig.loaderBrowser.baseURL
                                          ^

TypeError: Cannot read property 'baseURL' of undefined
    at Object.<anonymous> (...ui/node_modules/jspm-dev-server/bin/jspm-dev-server:31:43)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by mikz** [comment]
Yes. I just released 0.4.1.

**Comment by mikz** [comment]
See #8
